language: generic

# required super user access
sudo: required

# services thhat are required
services: 
  - docker

# series of steps ran before the test
before_install:
  - docker build -t rohithvazhathodiyil/docker-react -f Dockerfile.dev .

# triggering travis ci to run this script to have the test
script:
  - docker run -e CI=true rohithvazhathodiyil/docker-react yarn test